Algoritmo "lista de exercicio 3"
var

valorA, valorB, C: inteiro

inicio

escreval("digite o primeiro valor")
 leia(valorA)
  escreval("digite o segundo valor")
   leia(valorB)

se (valorA = valorB) entao
C <- valorA + valorB
escreval("valores iguais se somam, resultado: ", C)
senao
C <- valorA * valorB
escreval("valores diferentes se multiplicam, resultado: ", C)
fimse

Fimalgoritmo